# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_packages:

r_github_packages:
  - jimhester/covr

addons:
  apt:
    packages:
      - valgrind

before_install:

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
  - bash <(R -d "valgrind --tool=memcheck --leak-check=full" --vanilla < .tests/testthat.R)
