language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
      compiler: gcc
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      r: release
      compiler: clang

    - os: linux
      r: devel
      compiler: gcc
      before_install:
        - mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars

    - os: linux
      r: devel
      dist: trusty
      compiler: gcc
      sudo: required

    - os: linux
      r: devel
      dist: trusty
      compiler: clang
      sudo: required

    - os: linux
      r: release
      r_check_args: --as-cran --use-valgrind
      addons:
        apt:
          packages:
            - valgrind

    - os: osx
      r: release
      latex: false
      r_build_args: --no-build-vignettes
      r_check_args: --ignore-vignettes --no-examples

    - os: osx
      r: devel
      latex: false
      r_build_args: --no-build-vignettes
      r_check_args: --ignore-vignettes --no-examples

  allow_failures:
    - os: linux
      r: oldrel

