# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

env:

matrix:
  include:
  - r: release
  allow_failures:
  - r: oldrel
  - r: devel

r_packages:

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
