# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel

r_packages:

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
