language: r
sudo: false
cache: packages
r_check_args: --as-cran

matrix:
  include:
    - os: linux
      r: release
      r_packages: covr
      after_success: Rscript -e 'covr::codecov()'
    - os: linux
      r: devel
      before_install:
        mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars
    - os: linux
      r: release
      r_check_args: --as-cran --use-valgrind
      addons:
        apt:
          packages:
            - valgrind
      env: NB='w/ valgrind
    - os: osx
      r: release
      latex: false
      r_check_args: --as-cran --ignore-vignettes
    - os: osx
      r: devel
      latex: false
      r_check_args: --as-cran --ignore-vignettes

