version: "3"

vars:
  PKGNAME: qualpalr
  PKGSRC: .

tasks:
  clean:
    cmds:
      - rm -rf src/*.o src/*.so

  document:
    cmds:
      - Rscript -e 'devtools::document(roclets = c("rd", "collate", "namespace"))'

  build:
    deps: [document]
    cmds:
      - R CMD build --no-manual .

  build-cran:
    deps: [document]
    cmds:
      - R CMD build .

  install:
    cmds:
      - R CMD INSTALL --no-multiarch --with-keep.source .

  clean-install:
    deps: [document]
    cmds:
      - R CMD INSTALL --preclean --no-multiarch --with-keep.source .

  check:
    deps: [document]
    cmds:
      - Rscript -e 'devtools::check()'

  test:
    deps: [install]
    cmds:
      - Rscript -e 'devtools::test()'

  readme:
    cmds:
      - Rscript -e 'rmarkdown::render("README.Rmd")'
      - rm -rf README.html

  vignettes:
    cmds:
      - Rscript -e 'devtools::build_vignettes()'

  update-lib:
    desc: Fetch current release of c++ library component
    vars:
      API_URL: https://api.github.com/repos/jolars/qualpal/releases/latest
      RELEASE:
        sh: curl -s {{.API_URL}} | jq -r .tarball_url
    cmds:
      - mkdir -p tmp
      - mkdir -p inst/include
      - curl -L {{.RELEASE}} | tar -xz --strip-components=1 -C tmp
      - rm -rf src/qualpal
      - cp -ri tmp/src/qualpal src/
      - rm -rf inst/include/qualpal
      - rm -rf inst/include/qualpal.h
      - cp -ri tmp/include inst/
      - rm -rf tmp
