// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// qualpalr.cpp
cpp11::writable::list qualpal_cpp_rgb(int n, cpp11::doubles_matrix<> rgb_in, cpp11::list options);
extern "C" SEXP _qualpalr_qualpal_cpp_rgb(SEXP n, SEXP rgb_in, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(qualpal_cpp_rgb(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(rgb_in), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(options)));
  END_CPP11
}
// qualpalr.cpp
cpp11::writable::list qualpal_cpp_colorspace(int n, cpp11::list colorspace, int n_points, cpp11::list options);
extern "C" SEXP _qualpalr_qualpal_cpp_colorspace(SEXP n, SEXP colorspace, SEXP n_points, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(qualpal_cpp_colorspace(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(colorspace), cpp11::as_cpp<cpp11::decay_t<int>>(n_points), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(options)));
  END_CPP11
}
// qualpalr.cpp
cpp11::writable::list qualpal_cpp_palette(int n, std::string palette, cpp11::list options);
extern "C" SEXP _qualpalr_qualpal_cpp_palette(SEXP n, SEXP palette, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(qualpal_cpp_palette(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<std::string>>(palette), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(options)));
  END_CPP11
}
// qualpalr.cpp
cpp11::writable::doubles_matrix<> convert_colors_cpp(cpp11::doubles_matrix<> colors, std::string from, std::string to);
extern "C" SEXP _qualpalr_convert_colors_cpp(SEXP colors, SEXP from, SEXP to) {
  BEGIN_CPP11
    return cpp11::as_sexp(convert_colors_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(colors), cpp11::as_cpp<cpp11::decay_t<std::string>>(from), cpp11::as_cpp<cpp11::decay_t<std::string>>(to)));
  END_CPP11
}
// qualpalr.cpp
cpp11::writable::list analyze_palette_cpp(cpp11::doubles_matrix<> rgb_in, cpp11::list options);
extern "C" SEXP _qualpalr_analyze_palette_cpp(SEXP rgb_in, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(analyze_palette_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(rgb_in), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(options)));
  END_CPP11
}
// qualpalr.cpp
cpp11::writable::list list_palettes_cpp();
extern "C" SEXP _qualpalr_list_palettes_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(list_palettes_cpp());
  END_CPP11
}
// qualpalr.cpp
cpp11::writable::strings get_palette_cpp(std::string palette);
extern "C" SEXP _qualpalr_get_palette_cpp(SEXP palette) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_palette_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(palette)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_qualpalr_analyze_palette_cpp",    (DL_FUNC) &_qualpalr_analyze_palette_cpp,    2},
    {"_qualpalr_convert_colors_cpp",     (DL_FUNC) &_qualpalr_convert_colors_cpp,     3},
    {"_qualpalr_get_palette_cpp",        (DL_FUNC) &_qualpalr_get_palette_cpp,        1},
    {"_qualpalr_list_palettes_cpp",      (DL_FUNC) &_qualpalr_list_palettes_cpp,      0},
    {"_qualpalr_qualpal_cpp_colorspace", (DL_FUNC) &_qualpalr_qualpal_cpp_colorspace, 4},
    {"_qualpalr_qualpal_cpp_palette",    (DL_FUNC) &_qualpalr_qualpal_cpp_palette,    3},
    {"_qualpalr_qualpal_cpp_rgb",        (DL_FUNC) &_qualpalr_qualpal_cpp_rgb,        3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_qualpalr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
