// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dist2
NumericMatrix dist2(NumericMatrix Ar);
RcppExport SEXP qualpalr_dist2(SEXP ArSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Ar(ArSEXP);
    rcpp_result_gen = Rcpp::wrap(dist2(Ar));
    return rcpp_result_gen;
END_RCPP
}
// edist
Rcpp::NumericMatrix edist(NumericMatrix mat);
RcppExport SEXP qualpalr_edist(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(edist(mat));
    return rcpp_result_gen;
END_RCPP
}
