// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// qualpal_cpp_rgb
Rcpp::List qualpal_cpp_rgb(int n, const Rcpp::NumericMatrix& rgb_in, const Rcpp::List& options);
RcppExport SEXP _qualpalr_qualpal_cpp_rgb(SEXP nSEXP, SEXP rgb_inSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type rgb_in(rgb_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(qualpal_cpp_rgb(n, rgb_in, options));
    return rcpp_result_gen;
END_RCPP
}
// qualpal_cpp_colorspace
Rcpp::List qualpal_cpp_colorspace(int n, const Rcpp::List& hsl_colorspace, const int n_points, const Rcpp::List& options);
RcppExport SEXP _qualpalr_qualpal_cpp_colorspace(SEXP nSEXP, SEXP hsl_colorspaceSEXP, SEXP n_pointsSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hsl_colorspace(hsl_colorspaceSEXP);
    Rcpp::traits::input_parameter< const int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(qualpal_cpp_colorspace(n, hsl_colorspace, n_points, options));
    return rcpp_result_gen;
END_RCPP
}
// qualpal_cpp_palette
Rcpp::List qualpal_cpp_palette(int n, const std::string& palette, const Rcpp::List& options);
RcppExport SEXP _qualpalr_qualpal_cpp_palette(SEXP nSEXP, SEXP paletteSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(qualpal_cpp_palette(n, palette, options));
    return rcpp_result_gen;
END_RCPP
}
// convert_colors
Rcpp::NumericMatrix convert_colors(const Rcpp::NumericMatrix& colors, const std::string& from, const std::string& to);
RcppExport SEXP _qualpalr_convert_colors(SEXP colorsSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(convert_colors(colors, from, to));
    return rcpp_result_gen;
END_RCPP
}
// analyze_palette_cpp
Rcpp::List analyze_palette_cpp(const Rcpp::NumericMatrix& rgb_in, const Rcpp::List& options);
RcppExport SEXP _qualpalr_analyze_palette_cpp(SEXP rgb_inSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type rgb_in(rgb_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_palette_cpp(rgb_in, options));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qualpalr_qualpal_cpp_rgb", (DL_FUNC) &_qualpalr_qualpal_cpp_rgb, 3},
    {"_qualpalr_qualpal_cpp_colorspace", (DL_FUNC) &_qualpalr_qualpal_cpp_colorspace, 4},
    {"_qualpalr_qualpal_cpp_palette", (DL_FUNC) &_qualpalr_qualpal_cpp_palette, 3},
    {"_qualpalr_convert_colors", (DL_FUNC) &_qualpalr_convert_colors, 3},
    {"_qualpalr_analyze_palette_cpp", (DL_FUNC) &_qualpalr_analyze_palette_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_qualpalr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
