# Generated by cpp11: do not edit by hand

qualpal_cpp_rgb <- function(n, rgb_in, options) {
  .Call(`_qualpalr_qualpal_cpp_rgb`, n, rgb_in, options)
}

qualpal_cpp_colorspace <- function(n, colorspace, n_points, options) {
  .Call(`_qualpalr_qualpal_cpp_colorspace`, n, colorspace, n_points, options)
}

qualpal_cpp_palette <- function(n, palette, options) {
  .Call(`_qualpalr_qualpal_cpp_palette`, n, palette, options)
}

convert_colors_cpp <- function(colors, from, to) {
  .Call(`_qualpalr_convert_colors_cpp`, colors, from, to)
}

analyze_palette_cpp <- function(rgb_in, options) {
  .Call(`_qualpalr_analyze_palette_cpp`, rgb_in, options)
}

list_palettes_cpp <- function() {
  .Call(`_qualpalr_list_palettes_cpp`)
}

get_palette_cpp <- function(palette) {
  .Call(`_qualpalr_get_palette_cpp`, palette)
}
