# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qualpal_cpp_rgb <- function(n, rgb_in, cvd_list) {
    .Call(`_qualpalr_qualpal_cpp_rgb`, n, rgb_in, cvd_list)
}

qualpal_cpp_colorspace <- function(n, hsl_colorspace, n_points, cvd_list) {
    .Call(`_qualpalr_qualpal_cpp_colorspace`, n, hsl_colorspace, n_points, cvd_list)
}

qualpal_cpp_palette <- function(n, palette, cvd_list) {
    .Call(`_qualpalr_qualpal_cpp_palette`, n, palette, cvd_list)
}

#' Convert colors between colorspaces
#'
#' @param colors A matrix of colors
#' @param from The colorspace of the input colors, one of "rgb", "hsl",
#'   "din99d", "lab", "xyz"
#' @param to The colorspace of the output colors,
#'   one of "rgb", "hsl", "lab", "xyz"
#'
#' @return The colors converted to the new colorspace
convert_colors <- function(colors, from, to) {
    .Call(`_qualpalr_convert_colors`, colors, from, to)
}

